[package]
name = "wasm-simd"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[lib]
bench = false

[[test]]
name = "integration"
path = "tests/i32x4_tests.rs"

[dev-dependencies]
wasm-bindgen = "0.2.100"
wasm-bindgen-test = "0.3.50"